version: '3'

services:
  redis-0:
    container_name: redis-0
    image: redis:6.0.10
    ports:
      - '6379:6379'
    volumes:
      - "./redis0/redis.conf:/etc/redis/redis.conf"
    command:
      - redis-server
      - /etc/redis/redis.conf
    networks:
      - redis-cluster-network
  redis-1:
    container_name: redis-1
    image: redis:6.0.10
    ports:
      - '6380:6379'
    volumes:
      - "./redis1/redis.conf:/etc/redis/redis.conf"
    command:
      - redis-server
      - /etc/redis/redis.conf
    depends_on:
      - redis-0
    networks:
      - redis-cluster-network
  redis-2:
    container_name: redis-2
    image: redis:6.0.10
    ports:
      - '6381:6379'
    volumes:
      - "./redis2/redis.conf:/etc/redis/redis.conf"
    command:
      - redis-server
      - /etc/redis/redis.conf
    depends_on:
      - redis-0
    networks:
      - redis-cluster-network
  sentinel-0:
    container_name: sentinel-0
    image: redis:6.0.10
    volumes:
      - "./sentinel0/sentinel.conf:/etc/redis/sentinel.conf"
    command:
      - redis-sentinel
      - /etc/redis/sentinel.conf
    depends_on:
      - redis-0
    networks:
      - redis-cluster-network
  sentinel-1:
    container_name: sentinel-1
    image: redis:6.0.10
    volumes:
      - "./sentinel1/sentinel.conf:/etc/redis/sentinel.conf"
    command:
      - redis-sentinel
      - /etc/redis/sentinel.conf
    depends_on:
      - redis-0
    networks:
      - redis-cluster-network
  sentinel-2:
    container_name: sentinel-2
    image: redis:6.0.10
    volumes:
      - "./sentinel2/sentinel.conf:/etc/redis/sentinel.conf"
    command:
      - redis-sentinel
      - /etc/redis/sentinel.conf
    depends_on:
      - redis-0
    networks:
      - redis-cluster-network

networks:
  redis-cluster-network:
    driver: bridge