version: '3'

services:
  redis-0:
    container_name: redis-0
    image: redis:6.0.10
    ports:
      - '6379:6379'
    volumes:
      - "./data/:/data"
    command:
      - redis-server
  redis-1:
    container_name: redis-1
    image: redis:6.0.10
    ports:
      - '6380:6379'
    # volumes:
    #   - "./data/:/data"
    command:
      - redis-server
